/:
    template: blog/overview.twig
    variables:
        title: Blog
        overviewTitle: programming
        posts: src/content/blog.yaml
        meta:
            description: "My personal thoughts on the web and programming."
    config:
        order:
            variable: posts
            field: date
            direction: desc

/blog/page-{page}:
    template: blog/overview.twig
    variables:
        title: Blog
        overviewTitle: programming
        posts: src/content/blog.yaml
        meta:
            description: "My personal thoughts on the web and programming."
    config:
        pagination:
            variable: posts
            perPage: 100
            parameter: page
        order:
            variable: posts
            field: date
            direction: desc

/blog/{id}:
    template: blog/detail.twig
    variables:
        overviewTitle: programming
        post: src/content/blog.yaml
        meta:
            description: "My personal thoughts on the web and programming."
    config:
        collection:
            variable: post
            parameter: id
        next: true
        meta: true

/cookies:
    template: blog/detail.twig
    variables:
        post: src/content/cookies.yaml

/podcasts/all:
    template: blog/overview.twig
    variables:
        detailUrl: /podcasts
        overviewTitle: podcasts
        title: Podcasts
        posts: src/content/podcasts.yaml
        meta:
            description: "Podcast reviews — Listen. Critically."

/podcasts/{id}:
    template: blog/detail.twig
    variables:
        overviewUrl: /podcasts/all
        detailUrl: /podcasts
        post: src/content/podcasts.yaml
        meta:
            description: "Podcast reviews — Listen. Critically."
    config:
        collection:
            variable: post
            parameter: id
        next: true

/newsletter:
    template: newsletter/index.twig
    variables:
        posts: src/content/newsletter.yaml
        title: Newsletter
        meta:
            description: An archive of all my newsletters
    config:
        order:
            variable: posts
            field: date
            direction: desc

/laravel-beyond-crud:
    template: blog/overview_tag.twig
    variables:
        title: Laravel beyond CRUD
        posts: src/content/blog.yaml
        meta:
            description: "A blog series about managing larger Laravel projects"
    config:
        order:
            variable: posts
            field: date
            direction: asc
        filter:
            posts:
                book: true

/php-74:
    template: blog/overview_tag.twig
    variables:
        title: PHP 7.4
        posts: src/content/blog.yaml
        intro: src/content/intro/php-74.md
        meta:
            description: "Short closures, typed properties, preloading and more"
    config:
        order:
            variable: posts
            field: date
            direction: desc
        filter:
            posts:
                tag: php-74

/favicon:
    template: favicon.twig
