/:
    template: home.twig
    variables:
        hero: resources/img/hero.jpg
        title: Home
        posts: resources/content/blog.yaml
        meta:
            title: 'Stitcher 2: high performance static websites with PHP.'

/blog/page-{page}:
    template: blog/overview.twig
    variables:
        posts: resources/content/blog.yaml
    config:
        pagination:
            variable: posts
            perPage: 7
            parameter: page

/blog/{id}:
    template: blog/detail.twig
    variables:
        post: resources/content/blog.yaml
    config:
        collection:
            variable: post
            parameter: id

/guide/{id}:
    template: guide/detail.twig
    variables:
        page: resources/content/guide.yaml
        pages: resources/content/guide.yaml
    config:
        collection:
            variable: page
            parameter: id
        guide:
            variable: pages
