/:
    template: blog/overview.twig
    variables:
        title: Blog
        posts: src/content/blog.yaml
        meta:
            description: "My personal thoughts on the web and programming."
    config:
        order:
            variable: posts
            field: date
            direction: desc

/blog/page-{page}:
    template: blog/overview.twig
    variables:
        title: Blog
        posts: src/content/blog.yaml
        meta:
            description: "My personal thoughts on the web and programming."
    config:
        pagination:
            variable: posts
            perPage: 100
            parameter: page
        order:
            variable: posts
            field: date
            direction: desc

/blog/{id}:
    template: blog/detail.twig
    variables:
        post: src/content/blog.yaml
        meta:
            description: "My personal thoughts on the web and programming."
    config:
        collection:
            variable: post
            parameter: id
        next: true
