/:
    template: blog/overview.twig
    variables:
        posts: src/content/blog.yaml
    config:
        order:
            variable: posts
            field: date
            order: desc

/blog/page-{page}:
    template: blog/overview.twig
    variables:
        posts: src/content/blog.yaml
    config:
        pagination:
            variable: posts
            perPage: 100
            parameter: page
        order:
            variable: posts
            field: date
            order: desc

/blog/{id}:
    template: blog/detail.twig
    variables:
        post: src/content/blog.yaml
    config:
        collection:
            variable: post
            parameter: id

/guide/{id}:
    template: guide/detail.twig
    variables:
        page: src/content/guide.yaml
        pages: src/content/guide.yaml
    config:
        collection:
            variable: page
            parameter: id
        guide:
            variable: pages

/about:
    template: about.twig
    variables:
        content: src/content/about.md
        meta:
            title: About Stitcher and myself
            description: "A little information about myself and my favourite project: Stitcher"

/meta:
    template: meta.twig
