/:
    template: blog/overview.twig
    variables:
        title: Blog
        posts: src/content/blog.yaml
    config:
        order:
            variable: posts
            field: date
            direction: desc

/blog/page-{page}:
    template: blog/overview.twig
    variables:
        title: Blog
        posts: src/content/blog.yaml
    config:
        pagination:
            variable: posts
            perPage: 100
            parameter: page
        order:
            variable: posts
            field: date
            direction: desc

/blog/{id}:
    template: blog/detail.twig
    variables:
        post: src/content/blog.yaml
    config:
        collection:
            variable: post
            parameter: id

/blog/meta/{id}:
    template: meta.twig
    variables:
        post: src/content/blog.yaml
    config:
        collection:
            variable: post
            parameter: id

/meta:
    template: meta.twig
